baseURL: "https://mattselkey.com"
languageCode: "en-gb"
title: "MattSelkey"
theme: "hugo-theme-stack"

Params:
  mainSections:
  - posts
  showWordCount: true
  showReadingTime: true
  defaultTheme: auto
  showCodeCopyButtons: true
  showShareButtons: true
  showtoc: true
  hideFooter: true # hide the footer from the theme

  googleAnalytics:
    enabled: false
    trackingID: ''

  socialIcons:
    - name: github
      url: 'https://github.com/cwrenhold'
    - name: linkedin
      url: 'https://www.linkedin.com/in/catherine-wrenhold-84a58623a'

  article:
    toc: true

  sidebar:
    compact: false
    avatar:
      enabled: true
      local: true
      src: 'img/avatar.jpg'
    subtitle: >-
      IT | Scripting | Automation | Coding | Endurance Sport

  homeInfoParams:
    title: Blog
    content: >-
      IT | Scripting | Automation | Coding | Endurance Sport

  widgets:
    homepage: 
      - type: search
      - type: archives
        params:
          limit: 5
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark
menu:
   main: []
   
   social:
      ## see https://tabler.io/icons
    - identifier: github
      name: GitHub
      url: 'https://github.com/mattselkey'
      weight: 20
      params:
        icon: brand-github
    - identifier: linkedin
      name: LinkedIn
      url: 'https://www.linkedin.com/in/matthewselkirkkey/'
      weight: 30
      params:
        icon: brand-linkedin

markup:
  highlight:
    lineNos: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml