version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --future --incremental --watch --force_polling --verbose --livereload
    ports:
          - 4000:4000
    working_dir: /usr/src/app
    volumes:
         - .:/usr/src/app